clear;
clc;
z=[-5:0.1:5];
[a,k]=size(z);
s=zeros(1,k);
s=act_fuction ('sigmoid',z,k);
subplot(2,2,1);
plot(z,s);
title('sigmoid');
s=act_fuction ('tanh',z,k);
subplot(2,2,2);
plot(z,s);
title('tanh');
s=act_fuction ('relu',z,k);
subplot(2,2,3);
plot(z,s);
title('relu');
s=act_fuction ('softmax',z,k);
subplot(2,2,4);
plot(z,s);
title('softmax');